#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : glu
Version  : 9.0.0
Release  : 1
URL      : ftp://ftp.freedesktop.org/pub/mesa/glu/glu-9.0.0.tar.gz
Source0  : ftp://ftp.freedesktop.org/pub/mesa/glu/glu-9.0.0.tar.gz
Summary  : Mesa OpenGL Utility library
Group    : Development/Tools
License  : SGI-B-1.0
Requires: glu-lib
BuildRequires : mesa-dev
BuildRequires : pkgconfig(gl)

%description
No detailed description available

%package dev
Summary: dev components for the glu package.
Group: Development
Requires: glu-lib
Provides: glu-devel

%description dev
dev components for the glu package.


%package lib
Summary: lib components for the glu package.
Group: Libraries

%description lib
lib components for the glu package.


%prep
%setup -q -n glu-9.0.0

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/GL/glu.h
/usr/include/GL/glu_mangle.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
